// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwiwzadqizmnptwlxasj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3aXd6YWRxaXptbnB0d2x4YXNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NDE0NTEsImV4cCI6MjA1OTAxNzQ1MX0.zSMLykoj6cIQl8rq5lyfa_Wd2AkPVGhgmk3QNQ68CVI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);